services:
  air-quality-monitor:
    build: .
    container_name: air-quality-monitor
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - TZ=Europe/Paris
      - JAVA_OPTS=-Xmx1g -Xms512m -XX:+UseG1GC
    volumes:
      - air-quality-logs:/app/logs
      - air-quality-data:/app/data
    networks:
      - air-quality-network
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: air-quality-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    networks:
      - air-quality-network

  grafana:
    image: grafana/grafana:latest
    container_name: air-quality-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - air-quality-network
    depends_on:
      - prometheus

networks:
  air-quality-network:
    driver: bridge

volumes:
  air-quality-logs:
  air-quality-data:
  prometheus-data:
  grafana-data: